name: datathons-2
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - cartopy=0.20.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=35.0.0
  - curl=7.79.1
  - cycler=0.11.0
  - dash=2.0.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - elementpath=2.3.2
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - flask=2.0.2
  - flask-compress=1.10.1
  - folium=0.12.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.3
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.1
  - ipykernel=6.4.2
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - itsdangerous=2.0.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.15
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgdal=3.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - munch=2.5.0
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nspr=4.32
  - nss=3.71
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.3.4
  - parso=0.8.2
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - plotly=5.3.1
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - prompt-toolkit=3.0.22
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pydantic=1.8.2
  - pygments=2.10.0
  - pyod=0.9.5
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyproj=3.2.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - rtree=0.9.7
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.5.3
  - shapely=1.8.0
  - six=1.16.0
  - sqlite=3.36.0
  - statsmodels=0.13.0
  - tenacity=8.0.1
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - werkzeug=2.0.1
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2021.11.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - jsonschema==4.2.1
    - llvmlite==0.37.0
    - missingno==0.5.0
    - nbformat==5.1.3
    - numba==0.54.1
    - numpy==1.20.3
    - pyrsistent==0.18.0
    - seaborn==0.11.2
